.TH MON 1
.SH NAME
mon \- manage OP5 MONITOR
.SH SYNOPSIS
.B mon [-h] | \fBcommand\fR [\fBoptions\fR]... [\fBcommand\fR]
.SH DESCRIPTION
.B mon
is used to manually stop and start the \fImonitor\fR system processes, and to set up a distributed and/or load balanced environment.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display a friendly help message.
.SH COMMANDS
.SS START
.TP
.BR mon\ start
Start \fImonitor\fR and \fImerlind\fR system processes.
.SS STOP
.TP
.BR mon\ stop
Stop \fImonitor\fR and \fImerlind\fR system processes.
.SS RESTART
.TP
.BR mon\ restart
Restart \fImonitor\fR and \fImerlind\fR system processes.
.SS ASCII
Documentation coming soon.
.SS CHECK
Documentation coming soon.
.SS DB
Documentation coming soon.
.SS ECMD
.nf
.SS search
.TP
.BR mon\ ecmd\ search\ \fIregex\fR
Prints
.I templates
for all available commands matching \fIregex\fR.
The search is case insensitive.
.SS submit
.TP
.BR mon\ ecmd\ submit\ \fI[options]\fR\ \fIcommand\fR\ \fIargument\ ...\fR
Submits a
.I command
to the monitoring engine using the supplied \fIargument(s)\fr.
.SS LOG
.SS show
.TP
.BR mon\ log\ show\ \fIargument\ ...\fR
Runs the \fIshowlog\fR helper program.
Arguments passed to this command will be sent to the \fIshowlog\fR helper.
For more information, a help text can be found by running the command like this:
.TP
.BR mon\ log\ show\ \-\-help
.SS MT
Documentation coming soon.
.SS NODE
.SS add
.TP
.BR mon\ node\ add\ \fR<name>\fB\ \-\-type=[peer|poller|master]\fR\ [var\fIN\fR=\fIvalue\fR]
Adds a node with the designated
.I type
and
.I variables.
.SS ctrl
.nf
.B mon\ node\ ctrl\fR\\
<name>\ ...\ \fB[--self|all|--type=[peer|poller|master]]\ \-\-\fR\ \fIcommand\fR
.fi
.PP
Executes \fIcommand\fR on the [remote] node(s) names.
.SS OCONF
Documentation coming soon.
.SS QH
Documentation coming soon.
.SS QUERY
Documentation coming soon.
.SS SOP
Documentation coming soon.
.SS SSHKEY
Documentation coming soon.
.SS STATUS
Documentation coming soon.
.SS SYSCONFIG
Documentation coming soon.
.SH EXAMPLE
.TP
To check the status of all connected nodes, use the
.BR node\ status
command:
.PP
.nf
.RS
mon node status
.RE
.fi
.PP
.TP
To add a new service comment for the service \fIPING\fR on the host \fIfoo\fR would look something like this:
.PP
.nf
.RS
mon ecmd submit add_svc_comment service='foo;PING' \\
persistent=1 author='John Doe' comment='the comment'
.RE
.fi
.PP
