#!/bin/bash
prefix='/opt/monitor/op5/merlin'

modline=broker_module=/opt/monitor/op5/merlin/merlin.so
if grep "$modline" /opt/monitor/etc/nagios.cfg >/dev/null; then
	:
else
	echo "$modline /opt/monitor/op5/merlin/merlin.conf" \
		>> /opt/monitor/etc/nagios.cfg
fi
svccfg import /opt/monitor/svc/manifest-merlin.xml
