post:
  install:
    - mysql-devel
    - ruby20-devel
    - ruby-devel
    - python-nose
  steps: |
    mkdir --parents --mode=777 /mnt/logs/merlin_dtest
    mon test dist --basepath=/mnt/logs/merlin_dtest
    mon test rsync
    rm --force --recursive /mnt/logs/merlin_dtest
    # fake asmonitor rights since we don't want to depend on monitor-nacoma
    # for op5-naemon, asmonitor should be moved to op5-monitor-user package
    echo 'Defaults>monitor !requiretty' > /etc/sudoers.d/asmonitor
    echo 'ALL ALL=(monitor) NOPASSWD: ALL' >> /etc/sudoers.d/asmonitor
    chmod 440 /etc/sudoers.d/asmonitor
    sudo -u monitor mon test rsync

    # Run unit tests
    nosetests --nocapture --where apps/libexec/modules

    # Verify file permissions after installation
    stat --printf='%U:%G %a' /opt/monitor/op5/merlin/merlin.conf | xargs -I{} test "root:apache 640" = "{}"

    # Install requirements for cucumber test
    if [ -f /usr/bin/systemctl ]; then
      gem install --no-ri --no-rdoc cucumber:1.3.6 rspec:2.14.1 parallel_tests syntax:1.0.0 sequel mysql2
    else
      gem2.0 install --no-ri --no-rdoc cucumber:1.3.6 rspec:2.14.1 parallel_tests syntax:1.0.0 sequel mysql2
    fi

    # Run cucumber tests
    ulimit -c unlimited
    mkdir -p /mnt/logs
    echo "core ulimit: \$(ulimit -c)"
    cucumber --strict --format html --out /mnt/logs/cucumber.html --format pretty
