vm-config: |
  {"numCPUs": 4}
post:
  steps: |
    set -x
    mkdir --parents --mode=777 /mnt/logs/merlin_dtest
    mon test dist --basepath=/mnt/logs/merlin_dtest
    mon test rsync
    rm --force --recursive /mnt/logs/merlin_dtest
    sudo -u monitor mon test rsync

    # Run unit tests
    pushd /mnt/git/apps/libexec
    python3 -m pytest
    popd

    # Verify file permissions after installation
    stat --printf='%U:%G %a' /opt/monitor/op5/merlin/merlin.conf | xargs -I{} test "root:apache 660" = "{}"

    gpg2 --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    curl -sSL https://get.rvm.io | bash -s stable
    source /usr/local/rvm/scripts/rvm
    rvm install 2.7
    rvm use 2.7 --default
    ruby -v

    # Install requirements for cucumber test
    gem install --no-document bundler -v '~> 2.4.22'
    bundle install

    # Run cucumber tests
    ulimit -c unlimited
    mkdir -p /mnt/logs

    cucumber ${VERBOSE:+-v} --strict --format html \
        --out /mnt/logs/cucumber.html --format pretty\
        --tags ~@encrypted
    # Run the test suite again, but with encryption enabled
    # Some tests has been disabled. These tests pass just fine when running the
    # test suite with encryption enabled only, but for some reason fail when
    # running after the above test, without encryption enabled. Further the
    # disabled tests do not have any peers/pollers so encryption shouldn't
    # affect them.
    mon merlinkey generate
    export MERLIN_ENCRYPTED=TRUE
    export MERLIN_PUBKEY=/opt/monitor/op5/merlin/key.pub
    export MERLIN_PRIVKEY=/opt/monitor/op5/merlin/key.priv
    cucumber ${VERBOSE:+-v} --strict --format html \
        --out /mnt/logs/cucumber_encrypted.html \
        --format pretty --exclude "report_data" --tags ~@unstable --tags ~@unencrypted
