vm-config: |
  {"numCPUs": 4}
post:
  steps: |
    set -x
    mkdir --parents --mode=777 /mnt/logs/merlin_dtest
    mon test dist --basepath=/mnt/logs/merlin_dtest
    mon test rsync
    rm --force --recursive /mnt/logs/merlin_dtest
    sudo -u monitor mon test rsync

    # Run unit tests
    pushd /mnt/git/apps/libexec
    python3 -m pytest
    popd

    # Verify file permissions after installation
    stat --printf='%U:%G %a' /opt/monitor/op5/merlin/merlin.conf | xargs -I{} test "root:apache 660" = "{}"

    # Install requirements for cucumber test
    gem install --no-ri --no-rdoc \
        mysql2 \
        cucumber:1.3.18 \
        rspec:2.14.1 \
        parallel:1.19.2 \
        syntax:1.0.0 \
        sequel:5.71.0

    # Run cucumber tests
    ulimit -c unlimited
    mkdir -p /mnt/logs

    cucumber ${VERBOSE:+-v} --strict --format html \
        --out /mnt/logs/cucumber.html --format pretty\
        --tags ~@encrypted
    # Run the test suite again, but with encryption enabled
    # Some tests has been disabled. These tests pass just fine when running the
    # test suite with encryption enabled only, but for some reason fail when
    # running after the above test, without encryption enabled. Further the
    # disabled tests do not have any peers/pollers so encryption shouldn't
    # affect them.
    mon merlinkey generate
    export MERLIN_ENCRYPTED=TRUE
    export MERLIN_PUBKEY=/opt/monitor/op5/merlin/key.pub
    export MERLIN_PRIVKEY=/opt/monitor/op5/merlin/key.priv
    cucumber ${VERBOSE:+-v} --strict --format html \
        --out /mnt/logs/cucumber_encrypted.html \
        --format pretty --exclude "report_data" --tags ~@unstable --tags ~@unencrypted
