post:
  install:
    - mysql-devel
    - ruby20-devel
    - python-nose
  steps: |
    mkdir -p -m 777 /mnt/logs/merlin_dtest
    mon test dist --basepath=/mnt/logs/merlin_dtest
    mon test rsync
    # fake asmonitor rights since we don't want to depend on monitor-nacoma
    # for op5-naemon, asmonitor should be moved to op5-monitor-user package
    echo 'Defaults>monitor !requiretty' > /etc/sudoers.d/asmonitor
    echo 'ALL ALL=(monitor) NOPASSWD: ALL' >> /etc/sudoers.d/asmonitor
    chmod 440 /etc/sudoers.d/asmonitor
    sudo -u monitor mon test rsync

    # Run unit tests
    nosetests --nocapture --where apps/libexec/modules

    # Install requirements for cucumber test
    gem2.0 install sequel mysql2
