name: Github Pages

on:
  workflow_dispatch:



jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Install doc dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-sphinx python3-sphinx-rtd-theme python3-pip
          sudo pip install myst-parser
      - name: Make docs
        run: cd docs && make html
      - name: test
        run: ls -la && ls -la ./docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
